### ISSUE TITLE
Absence of appSettings.json causes ArgumentNullException

### ISSUE THREAD

**Issue by JanLenoch** [Kentico/cloud-generators-net#62]
at System.IO.Path.GetFullPath(String path)
   at CloudModelGenerator.CodeGenerator..ctor(IOptions`1 options) in C:\projects\cloud-generators-net\src\CloudModelGenerator\CodeGenerator.cs:line 27
   at CloudModelGenerator.Program.Execute(ArgumentSyntax argSyntax) in C:\projects\cloud-generators-net\src\CloudModelGenerator\Program.cs:line 83
   at CloudModelGenerator.Program.Main(String[] args) in C:\projects\cloud-generators-net\src\CloudModelGenerator\Program.cs:line 33

**Comment by Simply007** [comment]
This exception was raised when no appConfig.json nor in command line parameter outputDir was not set, but in docu what written that default value is "./"

Fixed and covered by tests.
